<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>ASP.NET Core endpoint adapter for experimental SAPI/0.1.</Description>
    <PackageReadmeFile>PACKAGE.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../SApi.Protocol/SApi.Protocol.csproj" />
    <None Include="PACKAGE.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
