<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <Description>SAPi handler and routing adapter for classic ASP.NET.</Description>
    <PackageReadmeFile>PACKAGE.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net462" Version="1.0.3" PrivateAssets="all" />
    <Reference Include="System.Web" />
    <Reference Include="System.Net.Http" />
    <ProjectReference Include="../SApi.Protocol/SApi.Protocol.csproj" />
    <None Include="PACKAGE.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
